Optimiser le processus de construction de l'image Docker : Mettre à jour le fichier Dockerfile et le workflow Docker

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -25,23 +25,33 @@ jobs:
           length: 6
 
       - run: echo "SHA=${{ steps.short-sha.outputs.sha }}" >> $GITHUB_ENV
-      
+
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
-      
+
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v2
+        with:
+          platforms: linux/arm/v7,linux/arm64
+
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
         with:
           install: true
-      
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v2
-        with:
-          platforms: all
-      
+
+      - name: Debug environment variables
+        run: |
+          echo "Environment variables:"
+          env
+
+      - name: Debug Dockerfile
+        run: |
+          echo "Dockerfile content:"
+          cat ./Dockerfile
+
       - name: Build and push 32-bit image
         uses: docker/build-push-action@v5
         with:
@@ -52,7 +62,12 @@ jobs:
           build-args: ARCH=armv7
           file: ./Dockerfile
           platforms: linux/arm/v7
-      
+
+      - name: Debug 32-bit image build
+        run: |
+          echo "Inspecting 32-bit image:"
+          docker image inspect leto1210/duplicacy-web-arm:${{ env.SHA }}-armv7 || echo "Image not found"
+
       - name: Build and push 64-bit image
         uses: docker/build-push-action@v5
         with:
@@ -63,3 +78,8 @@ jobs:
           build-args: ARCH=arm64
           file: ./Dockerfile
           platforms: linux/arm64
+
+      - name: Debug 64-bit image build
+        run: |
+          echo "Inspecting 64-bit image:"
+          docker image inspect leto1210/duplicacy-web-arm:${{ env.SHA }}-arm64 || echo "Image not found"
